# Generated by Django 6.0.1 on 2026-02-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_is_active_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
