# Generated by Django 6.0.1 on 2026-02-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='special_day',
            field=models.IntegerField(blank=True, help_text='Auto special day (0=Mon … 6=Sun)', null=True),
        ),
    ]
